name: "PantryPad"
description: "PantryPad Add-On"
version: "0.1.3-beta.1"
slug: "pantrypad"
init: false
arch:
  - amd64
  - armv7
  - aarch64
  - i386
  - armhf
startup: services
webui: http://[HOST]:[PORT:8080]
image: ghcr.io/valadas/pantrypad
ports:
  8080/tcp: 8000