name: "PantryPad"
version: "0.1.3-beta.1"
slug: "pantrypad"
description: "PantryPad Add-On"
webui: http://[HOST]:[PORT:8080]
arch:
  - amd64
  - armv7
  - aarch64
  - i386
  - armhf
image: ghcr.io/valadas/pantrypad
ports:
  - 8080/tcp: 5000