name: "PantryPad"
version: "0.1.3-beta.1"
slug: "pantrypad"
description: "PantryPad Add-On"
startup: services
boot: auto
# webui: http://[HOST]:[PORT:8099]
arch:
  - amd64
  - armv7
  - aarch64
  - i386
  - armhf
ingress: true
ingress_port: 5000
ports: {}
image: ghcr.io/valadas/pantrypad
