name: "PantryPad"
version: "0.1.1.3"
slug: "pantrypad"
description: "PantryPad Add-On"
arch: 
    - amd64
    - armv7
    - aarch64
    - i386
    - armhf
ingress: true
ports:
    8099/tcp: 8099
image: ghcr.io/valadas/pantrypad
  