name: "PantryPad"
version: "0.1.3-beta.1"
slug: "pantrypad"
description: "PantryPad Add-On"
startup: services
boot: auto
# webui: http://[HOST]:[PORT:8099]
arch:
  - amd64
  - armv7
  - aarch64
  - i386
  - armhf
ingress: true
ingress_stream: true
ingress_port: 8080
ports:
  - 8080/tcp: null
  - 8099/tcp: null
  - 8443/tcp: null
map:
  - ssl
image: ghcr.io/valadas/pantrypad
