name: "PantryPad"
description: "PantryPad Add-On"
version: "0.1.5-beta.2"
slug: "pantrypad"
init: false
arch:
  - amd64
  - armv7
  - aarch64
  - i386
  - armhf
startup: services
image: ghcr.io/valadas/pantrypad
ingress: true
ingress_port: 8080
ingress_streaming: true